//
//  YSLocationBuilderTests.m
//  ystrdy
//
//  Created by Jabari on 9/4/13.
//  Copyright (c) 2013 23bit. All rights reserved.
//

#import "YSLocationBuilderTests.h"

@implementation YSLocationBuilderTests

static NSString *locationJSON = @"{"
@"response\": {"
    @"\"version\": \"0.1\","
    @"\"termsofService\": \"http://www.wunderground.com/weather/api/d/terms.html\","
    @"\"features\": {"
        @"\"geolookup\": 1"
    @"}"
@"},"
@"\"location\": {"
    @"\"type\": \"CITY\","
    @"\"country\": \"US\","
    @"\"country_iso3166\": \"US\","
    @"\"country_name\": \"USA\","
    @"\"state\": \"CA\","
    @"\"city\": \"San Francisco\","
    @"\"tz_short\": \"PDT\","
    @"\"tz_long\": \"America/Los_Angeles\","
    @"\"lat\": \"37.776289\","
    @"\"lon\": \"-122.395234\","
    @"\"zip\": \"94107\","
    @"\"magic\": \"1\","
    @"\"wmo\": \"99999\","
    @"\"l\": \"/q/zmw:94107.1.99999\","
    @"\"requesturl\": \"US/CA/San_Francisco.html\","
    @"\"wuiurl\": \"http://www.wunderground.com/US/CA/San_Francisco.html\","
    @"\"nearby_weather_stations\": {"
        @"\"airport\": {"
            @"\"station\": [{"
                @"\"city\": \"Oakland\","
                @"\"state\": \"CA\","
                @"\"country\": \"US\","
                @"\"icao\": \"KOAK\","
                @"\"lat\": \"37.72000122\","
                @"\"lon\": \"-122.22000122\""
            @"}, {"
                @"\"city\": \"San Francisco\","
                @"\"state\": \"CA\","
                @"\"country\": \"US\","
                @"\"icao\": \"KSFO\","
                @"\"lat\": \"37.61999893\","
                @"\"lon\": \"-122.37000275\""
            @"}, {"
                @"\"city\": \"Hayward\","
                @"\"state\": \"CA\","
                @"\"country\": \"US\","
                @"\"icao\": \"KHWD\","
                @"\"lat\": \"37.65999985\","
                @"\"lon\": \"-122.12000275\""
            @"}, {"
                @"\"city\": \"Half Moon Bay\","
                @"\"state\": \"CA\","
                @"\"country\": \"US\","
                @"\"icao\": \"KHAF\","
                @"\"lat\": \"37.50999832\","
                @"\"lon\": \"-122.50000000\""
            @"}]"
        @"},"
        @"\"pws\": {"
            @"\"station\": [{"
                @"\"neighborhood\": \"Mission Bay - My weather is better than yours.\","
                @"\"city\": \"San Francisco\","
                @"\"state\": \"CA\","
                @"\"country\": \"US\","
                @"\"id\": \"KCASANFR53\","
                @"\"distance_km\": 0,"
                @"\"distance_mi\": 0"
            @"}, {"
                @"\"neighborhood\": \"Potrero Hill\","
                @"\"city\": \"San Francisco\","
                @"\"state\": \"CA\","
                @"\"country\": \"US\","
                @"\"id\": \"KCASANFR108\","
                @"\"distance_km\": 1,"
                @"\"distance_mi\": 0"
            @"}, {"
                @"\"neighborhood\": \"Mid Richmond\","
                @"\"city\": \"San Francisco\","
                @"\"state\": \"CA\","
                @"\"country\": \"US\","
                @"\"id\": \"KCASANFR128\","
                @"\"distance_km\": 6,"
                @"\"distance_mi\": 4"
            @"}]"
        @"}"
    @"}"
@"}"
@"}\"";

@end
